#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs  state=tiled follow=on
#bspc rule -a firefox desktop='^3' state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a qv2ray state=floating
bspc rule -a jetbrains-idea state=floating
bspc rule -a mpv state=floating
bspc rule -a Gnome-system-monitor state=floating
bspc rule -a Zathura state=tiled
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a netease-cloud-music desktop='^10' state=floating follow=on
wmname LG3D

$HOME/.config/polybar/launch.sh
picom --experimental-backends -b
feh --bg-fill $DOT/wallpaper/wall.jpg
#killall dwall
#dwall -s=moon &
fcitx
nm-applet
dropbox

#Notification
pkill dunst
run_once dunst &

# lock screen
xautolock -time 10 -locker i3lock-fancy

libinput-gestures-setup start
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
greenclip daemon &
