#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs  state=tiled follow=on
#bspc rule -a firefox desktop='^3' state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Qv2ray state=floating
bspc rule -a mpv state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a netease-cloud-music desktop='^10' state=floating follow=on

$HOME/.config/polybar/launch.sh
picom -b
feh --bg-scale Pictures/Wallpapers/photo-1509460370682-bb161911847b.jpeg
fcitx
nm-applet
dropbox

#Notification
pkill dunst
run_once dunst &
